"""Structural layer: symbol/dependency graph, PageRank, repo map, neighbors.

Built in memory from the manifest's symbol metadata (call/import edges) - no
extra store. Call edges are name-based and approximate (Aider-style): they drive
ranking and "what calls this" hints, not a guaranteed-correct call graph.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np


@dataclass
class Graph:
    symbols: dict[str, dict]  # doc_key -> symbol info (incl. "file")
    name_index: dict[str, set]  # name -> {doc_key}
    out_edges: dict[str, set]  # caller -> {callee doc_key}
    in_edges: dict[str, set]  # callee -> {caller doc_key}
    files: dict[str, dict]  # relpath -> file entry (imports, symbols)


def file_to_module(relpath: str) -> str:
    base = relpath.rsplit(".", 1)[0]
    return base.replace("/", ".")


def build_graph(manifest: dict) -> Graph:
    files = manifest.get("files", {})
    symbols: dict[str, dict] = {}
    name_index: dict[str, set] = {}

    for relpath, fe in files.items():
        for key, sd in fe.get("symbols", {}).items():
            if "qualname" not in sd:  # chunk entries
                continue
            info = dict(sd)
            info["file"] = relpath
            symbols[key] = info
            name_index.setdefault(info["name"], set()).add(key)

    out_edges = {k: set() for k in symbols}
    in_edges = {k: set() for k in symbols}
    for key, info in symbols.items():
        for callee in info.get("calls", []):
            for tgt in name_index.get(callee, ()):
                if tgt == key:
                    continue
                out_edges[key].add(tgt)
                in_edges[tgt].add(key)

    return Graph(symbols, name_index, out_edges, in_edges, files)


def pagerank(graph: Graph, damping: float = 0.85, iters: int = 60, tol: float = 1e-9) -> dict[str, float]:
    nodes = list(graph.symbols)
    n = len(nodes)
    if n == 0:
        return {}
    idx = {k: i for i, k in enumerate(nodes)}
    targets = [[idx[t] for t in graph.out_edges[k]] for k in nodes]
    out_deg = np.array([len(t) for t in targets], dtype=float)
    rank = np.full(n, 1.0 / n)

    for _ in range(iters):
        new = np.full(n, (1.0 - damping) / n)
        dangling = 0.0
        for i in range(n):
            if out_deg[i] == 0:
                dangling += rank[i]
                continue
            share = damping * rank[i] / out_deg[i]
            for t in targets[i]:
                new[t] += share
        new += damping * dangling / n
        if np.abs(new - rank).sum() < tol:
            rank = new
            break
        rank = new

    return {k: float(rank[idx[k]]) for k in nodes}


def render_map(manifest: dict, ranks: dict[str, float], budget_tokens: int = 2000) -> str:
    files = manifest.get("files", {})
    by_file: dict[str, list] = {}
    for relpath, fe in files.items():
        for key, sd in fe.get("symbols", {}).items():
            if "qualname" not in sd:
                continue
            by_file.setdefault(relpath, []).append((sd, ranks.get(key, 0.0)))

    if not by_file:
        return "# Code map (auto-generated by intent-code)\n\n(no symbols indexed)\n"

    file_order = sorted(
        by_file, key=lambda f: (-max(r for _, r in by_file[f]), f)
    )

    budget_chars = max(budget_tokens, 200) * 4
    header = "# Code map (auto-generated by intent-code)\n"
    lines = [header, ""]
    used = len(header) + 1
    shown = 0
    for relpath in file_order:
        block = [f"## {relpath}"]
        for sd, _rank in sorted(
            by_file[relpath], key=lambda x: (-x[1], x[0]["start_line"])
        ):
            sig = sd.get("sig") or f"{sd['qualname']} ({sd['kind']})"
            block.append(f"- L{sd['start_line']}: {sig}")
        text = "\n".join(block) + "\n"
        if used + len(text) > budget_chars and shown > 0:
            remaining = len(file_order) - shown
            lines.append(f"_… {remaining} more file(s) omitted to fit the token budget_")
            break
        lines.append(text)
        used += len(text)
        shown += 1
    return "\n".join(lines)


def _resolve(graph: Graph, query: str) -> list[str]:
    if query in graph.symbols:
        return [query]
    exact = [k for k, sd in graph.symbols.items() if sd["qualname"] == query]
    if exact:
        return exact
    return [
        k
        for k, sd in graph.symbols.items()
        if sd["qualname"].endswith("." + query) or sd["name"] == query
    ]


def _node(graph: Graph, key: str, relation: str) -> dict:
    sd = graph.symbols[key]
    return {
        "doc_key": key,
        "qualname": sd["qualname"],
        "file": sd["file"],
        "kind": sd["kind"],
        "start_line": sd.get("start_line"),
        "relation": relation,
    }


def neighbors(graph: Graph, query: str, direction: str = "callees", k: int = 20) -> list[dict]:
    keys = _resolve(graph, query)
    out: list[dict] = []
    seen: set = set()

    for key in keys:
        if direction == "callees":
            for t in graph.out_edges.get(key, ()):
                if t not in seen:
                    seen.add(t)
                    out.append(_node(graph, t, "callee"))
        elif direction == "callers":
            for s in graph.in_edges.get(key, ()):
                if s not in seen:
                    seen.add(s)
                    out.append(_node(graph, s, "caller"))
        elif direction == "importers":
            f = graph.symbols[key]["file"]
            mod = file_to_module(f)
            cands = {mod, mod.split(".")[-1], ".".join(mod.split(".")[-2:])}
            for relpath, fe in graph.files.items():
                if relpath == f or relpath in seen:
                    continue
                imports = fe.get("imports", [])
                if any(any(c in imp for c in cands) for imp in imports):
                    seen.add(relpath)
                    out.append({"file": relpath, "relation": "importer"})
        else:
            raise ValueError(f"unknown direction {direction!r}")

    return out[:k]
