"""Rebuild an index under a different embedder without losing knowledge.

Switching embedders changes the vector dimension (hashing is 512, nomic-embed-text
is 768), and intent-db refuses to reopen a store whose stored dim disagrees with
the embedder. So adopting a newly available embedder means rebuilding the store.

Almost everything in the store is derived from the repo and is regenerated by the
full walk that follows a rebuild: source documents, the manifest, the repo map and
the intent pack. Three things are not, and are carried across here:

* note documents. The markdown lives in the knowledge directory, but `covers`,
  `covers_sha` and `stale` exist only in the store, so re-reading the files would
  silently drop staleness tracking.
* relevance feedback and the query log, which are the learning signal behind
  fusion weights.
* the learned fusion weights themselves.

Those tables key on `doc_key` and query text rather than row ids, so they survive
a rebuild intact. Their `created_at` timestamps are reset, since replaying goes
through the public API; only ordering matters to the consumers.
"""

from __future__ import annotations

import os
import uuid
from pathlib import Path
from typing import Any, Callable

from intentdb import IntentDB
from intentdb.store import Store

ProgressFn = Callable[[str], None]

#: SQLite writes these alongside the database in WAL mode
_SIBLING_SUFFIXES = ("-wal", "-shm")


def _discard(path: Path) -> None:
    """Remove a database file and any WAL siblings, ignoring what is not there."""
    for candidate in (path, *(Path(f"{path}{s}") for s in _SIBLING_SUFFIXES)):
        try:
            candidate.unlink()
        except FileNotFoundError:
            pass


def scratch_paths(db_path: Path) -> tuple[Path, Path]:
    """Per-attempt (rebuild, backup) paths.

    These must be unique per process. A fixed name means two concurrent rebuilds
    of the same repo write to the same file and delete each other's
    work-in-progress, which surfaces as a SQLite disk I/O error in whichever
    process was mid-write. With unique names the only shared step is the final
    atomic rename, where last writer wins and both results are valid.
    """
    token = f"{os.getpid()}.{uuid.uuid4().hex[:8]}"
    return (
        db_path.with_name(f"{db_path.name}.rebuild.{token}"),
        db_path.with_name(f"{db_path.name}.bak.{token}"),
    )


def _extract(db_path: Path) -> dict[str, Any]:
    """Read the carry-over state straight from SQLite, without an embedder.

    Going through Store rather than IntentDB matters: the stored spec may name an
    Ollama model that is currently unreachable, and building that embedder just to
    read rows would fail for no reason.
    """
    store = Store(str(db_path))
    try:
        _ids, keys, texts, metas, _matrix = store.load_all_documents()
        notes = [
            (text, key, meta)
            for key, text, meta in zip(keys, texts, metas)
            if (meta or {}).get("layer") == "note"
        ]
        return {
            "notes": notes,
            "feedback": store.load_feedback(),
            # load_query_log returns newest first; replay oldest first so the
            # rebuilt log keeps its original order.
            "query_log": list(reversed(store.load_query_log())),
            "fusion_weights": store.load_fusion_weights(),
        }
    finally:
        store.close()


def rebuild_with_embedder(
    db_path: str | Path,
    desired_spec: str,
    on_progress: ProgressFn | None = None,
) -> dict[str, Any]:
    """Rebuild the store at `db_path` under `desired_spec`.

    The caller must have closed its own connection first. Returns a summary of
    what was preserved. The original file is kept as a backup until the swap
    succeeds, and restored if anything fails, so an interrupted rebuild never
    leaves the repo without an index.
    """
    db_path = Path(db_path)
    if not db_path.exists():
        return {"rebuilt": False, "reason": "no existing index"}

    def report(message: str) -> None:
        if on_progress:
            on_progress(message)

    carried = _extract(db_path)
    report(
        f"rebuilding index under {desired_spec}: carrying {len(carried['notes'])} "
        f"note(s), {len(carried['feedback'])} feedback row(s), "
        f"{len(carried['query_log'])} logged quer(ies)"
    )

    tmp_path, backup = scratch_paths(db_path)
    _discard(tmp_path)

    try:
        idb = IntentDB(str(tmp_path), embedder=desired_spec)
        try:
            if carried["notes"]:
                idb.add_many(carried["notes"])
            for row in carried["feedback"]:
                idb.store.add_feedback(
                    row["query_text"],
                    row["doc_key"],
                    row.get("intent"),
                    bool(row.get("useful", True)),
                )
            for row in carried["query_log"]:
                idb.store.log_query(
                    row["text"], row.get("intent"), bool(row.get("inferred", False))
                )
            for intent_name, weights in carried["fusion_weights"].items():
                idb.store.upsert_fusion_weights(intent_name, weights, 0)
        finally:
            idb.close()
    except Exception:
        _discard(tmp_path)
        raise

    # Swap. The old database's WAL siblings must go before the new file takes its
    # name, otherwise SQLite would pair a fresh database with a stale write-ahead
    # log and corrupt it.
    _discard(backup)
    os.replace(db_path, backup)
    for suffix in _SIBLING_SUFFIXES:
        try:
            Path(f"{db_path}{suffix}").unlink()
        except FileNotFoundError:
            pass
    try:
        os.replace(tmp_path, db_path)
    except Exception:
        os.replace(backup, db_path)
        _discard(tmp_path)
        raise
    _discard(backup)

    summary = {
        "rebuilt": True,
        "embedder": desired_spec,
        "notes_preserved": len(carried["notes"]),
        "feedback_preserved": len(carried["feedback"]),
        "queries_preserved": len(carried["query_log"]),
        "fusion_weights_preserved": len(carried["fusion_weights"]),
    }
    report("rebuild complete")
    return summary
